# Site wide configuration

title: The Blog of Dr. Moron
locale: en_US
description: "I blog because there is no peer review like no peer review."
#logo: site-logo.png
search: true
url: 

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Denver

# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Kenneth Moreland
  avatar: kenneth-moreland-photo.jpg
  gravatar-hash:  a0ab8baa182c61ba892c4a8775b10001
  email: kmorel@sandia.gov
  disqus-shortname: kmorel
  twitter: #username
  facebook: "kenneth.moreland.7"
  github: "kmorel"
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: "kmorel"
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: "http://plus.google.com/101262760714548326608"
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
